### ISSUE TITLE
Refactor DAO methods

### ISSUE THREAD

**Issue by hacksparrow** [loopbackio/loopback-datasource-juggler#1867]
Currently, DAO methods don't have a uniform way of processing and generating the result model. Ideally, the model object should be generated by a single pipeline, which would be invoked by all the DAO methods that deal with data retrieval.

Take a look at the differences in how the model data is created in the callback function of these DAO methods:

create: https://github.com/strongloop/loopback-datasource-juggler/blob/261dd1c865e8b197882a161b909b90b0e6c3c2a3/lib/dao.js#L383
save: https://github.com/strongloop/loopback-datasource-juggler/blob/261dd1c865e8b197882a161b909b90b0e6c3c2a3/lib/dao.js#L2137
replaceById: https://github.com/strongloop/loopback-datasource-juggler/blob/261dd1c865e8b197882a161b909b90b0e6c3c2a3/lib/dao.js#L2700
find: https://github.com/strongloop/loopback-datasource-juggler/blob/261dd1c865e8b197882a161b909b90b0e6c3c2a3/lib/dao.js#L1622

If DAO methods do their own thing, implementing new features or bug fixes that center around the model object will require changes for each DAO method.

**Comment by dhmlau** [comment]
With the juggler-next work in mind, would it make more sense to ensure the consistency there? 

cc @bajtos @raymondfeng

**Comment by bajtos** [comment]
Yeah, I agree this is probably best to defer to juggler-refactor Epic.
