### ISSUE TITLE
Type issue

### ISSUE THREAD

**Issue by Anu1601CS** [loopbackio/loopback-datasource-juggler#1909]
## Steps to reproduce

Builds are failing it was working perfect sudden this issue came.

## Current Behavior

![image](https://user-images.githubusercontent.com/30978328/154896903-775998e7-3ef0-4600-9eea-2fba33e085d6.png)

## Expected Behavior

No errors

## Related Issues
No

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by achrinza** [comment]
Thanks for the report, currently verifying the issue at my end.

**Comment by achrinza** [comment]
As an immediate, temporary solution, add the following to your `package.json`:

```json
"overrides": {
  "@loopback/repository": {
    "loopback-datasource-juggler": "4.26.0"
  }
}
```

See https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides for more information on overrides.

**Comment by achrinza** [comment]
Hi @Anu1601CS, I've just tested this at my end with the `todo` example (via `lb4 example`) and was not able to replicate the issue (i.e. was able to build and start the application).

I've verified that `loopback-datasource-juggler@4.27.0` was in the dependency tree:

```sh
$ npm ls --depth=2 | grep -e '@loopback/repository@' -e 'loopback-datasource-juggler@'
│ │ ├── @loopback/repository@4.1.0 deduped
│ ├── @loopback/repository@4.1.0 deduped
├─┬ @loopback/repository@4.1.0
│ ├─┬ loopback-datasource-juggler@4.27.0
│ ├── loopback-datasource-juggler@4.27.0 deduped
```

I'm currently using Node.js v16.14.0.

**Comment by Anu1601CS** [comment]
Hi @achrinza 

```
npm ls --depth=2 | grep -e '@loopback/repository@' -e 'loopback-datasource-juggler@'

│ ├── @loopback/repository@1.19.1 deduped
│ │ ├── @loopback/repository@1.19.1 deduped
├─┬ @loopback/repository@1.19.1
│ └─┬ loopback-datasource-juggler@4.26.0
│ └── loopback-datasource-juggler@4.26.0 deduped
```

`Node  14x`

**Comment by achrinza** [comment]
Thanks for the additional info. It looks the `node_modules` you're testing against is still on `loopback-datasource-juggler@4.26.0`, which does not contain `geo.d.ts`, which means it should not be affected by the latest release (v4.27.0).

See:

- v4.27.0: https://github.com/loopbackio/loopback-datasource-juggler/tree/74d429d52d00f4c957c586112cb1257b1f01d0e2/types
- v4.26.0: https://github.com/loopbackio/loopback-datasource-juggler/tree/06428247ad1cc48bce82d135f795fb3eaae28b33/types

This hints to me that there may be some discrepencies with the CI pipeline (e.g. It is using `npm install` instead of `npm ci`). Could you please cross-check if the CI pipeline's dependency tree is the same?

It also seems that  an older version of `@loopback/repository` is being used. If feasible, could you test if upgrading the packages solve the issue? This can be done by updating the `lb4` CLI and using `lb4 update` in the project root directory:

```sh
$ npm install --global @loopback/cli
$ lb4 update
```

**Comment by Anu1601CS** [comment]
i  am looking into it

**Comment by amortega** [comment]
I am having the same problem, did you manage to solve it?

**Comment by dhivyapriya1998** [comment]
Hi,

I'm also facing the similar issue same as @Anu1601CS 
Before it was working fine before.

This is my project dependencies
 "dependencies": {
    "@highcharts/map-collection": "^2.0.0",
    "@loopback/authentication": "^4.1.3",
    "@loopback/boot": "^1.7.4",
    "@loopback/context": "^1.25.1",
    "@loopback/core": "^1.12.4",
    "@loopback/openapi-v3": "^1.13.0",
    "@loopback/repository": "^1.19.1",
    "@loopback/rest": "^1.26.1",
    "@loopback/rest-explorer": "^1.4.10",
    "@loopback/service-proxy": "^1.3.17",
    "@types/highcharts": "5.0.16",
    "@types/properties-reader": "0.0.2",
    "@types/puppeteer": "^2.0.1",
    "@types/winston": "^2.4.4",
    "axios": "^0.19.2",
    "dotenv": "^8.2.0",
    "fs-extra": "^8.1.0",
    "handlebars": "^4.7.6",
    "highcharts": "5.0.14",
    "http-errors": "^1.7.3",
    "keycloak-backend": "^2.0.1",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.33",
    "nodemailer": "^6.6.3",
    "nodemailer-express-handlebars": "^4.0.0",
    "path": "^0.12.7",
    "properties-reader": "^2.0.0",
    "puppeteer-core": "^3.0.0",
    "puppeteer-pdf": "^1.2.0",
    "save": "^2.4.0",
    "winston": "^3.3.3",
    "winston-daily-rotate-file": "^4.4.2",
    "xlsx": "^0.17.0"
  },
  "devDependencies": {
    "@loopback/build": "^2.1.0",
    "@loopback/eslint-config": "^4.1.5",
    "@loopback/testlab": "^1.10.3",
    "@types/node": "^10.17.20",
    "@types/puppeteer-core": "^2.0.0",
    "@typescript-eslint/eslint-plugin": "^2.29.0",
    "@typescript-eslint/parser": "^2.29.0",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.10.1",
    "eslint-plugin-eslint-plugin": "^2.2.1",
    "eslint-plugin-mocha": "^6.3.0",
    "nodemon": "^2.0.3",
    "source-map-support": "^0.5.17",
    "typescript": "^3.8.3"
  }
  
  In packagelock.json i could able to find loopback-datasource -juggler
     "loopback-datasource-juggler": {
      "version": "4.27.0",
      "resolved": "https://registry.npmjs.org/loopback-datasource-juggler/-/loopback-datasource-juggler-4.27.0.tgz",
      "integrity": "sha512-VbC2nt1Bmu/5P7Z9TR2SuQoca+dJCFCtW13mpkedXhNhlkJRDki369epcxQO0/3lVqjKaZx7usPDhwf+e22npA==",
      "requires": {
        "async": "^3.1.0",
        "change-case": "^4.1.1",
        "debug": "^4.1.0",
        "depd": "^2.0.0",
        "inflection": "^1.6.0",
        "lodash": "^4.17.11",
        "loopback-connector": "^5.0.0",
        "minimatch": "^3.0.3",
        "nanoid": "^3.1.20",
        "qs": "^6.5.0",
        "strong-globalize": "^6.0.5",
        "traverse": "^0.6.6",
        "uuid": "^8.3.1"
      },
      "dependencies": {
        "depd": {
          "version": "2.0.0",
          "resolved": "https://registry.npmjs.org/depd/-/depd-2.0.0.tgz",
          "integrity": "sha512-g7nH6P6dyDioJogAAGprGpCtVImJhpPk/roCzdb3fIh61/s/nPsfR6onyMwkCAR/OlC3yBC0lESvUoQEAssIrw=="
        }
      }
    },

**Comment by dhivyapriya1998** [comment]
@achrinza could you pls help on it

**Comment by achrinza** [comment]
Thanks for the additional information, @dhivyapriya1998. Could you provide the OS, Node.js version, and package manager (i.e. NPM) version? It also seems like you're using an older set of LB4 packages; If feasible, could you attempt to upgrade them to the latest versions? The update steps can be found in my previous comment: https://github.com/loopbackio/loopback-datasource-juggler/issues/1909#issuecomment-1046858506

@amortega Could you provide some information on your environment?

I'm currently trying to find what's commonality between these issues and why I'm not able to reproduce it at my end. So more information may help with pinpointing the issue.

---

As a quick reminder for those who need an immediate solution, please follow these steps: https://github.com/loopbackio/loopback-datasource-juggler/issues/1909#issuecomment-1046535504

**Comment by achrinza** [comment]
Please also provide the error that you're experiencing as well.

**Comment by achrinza** [comment]
I suspect that this may be caused by incompatibility between TypeScript versions. If possible, please update these packages:

- `typescript`
- `tslib`
- `@loopback/build` (Optional)

I'll continue to investigate and try to identify the root cause from my end.

**Comment by Winnetu** [comment]
for me just changing to typescript version 4.0.3 solved issue

**Comment by dhivyapriya1998** [comment]
@achrinza  
node - v14.17.0
npm - 6.14.13

**Comment by achrinza** [comment]
Thanks for all the information. I was able to confirm that the issue is with the use of Template Literal Types, which was [introduced in TypeScript 4.1](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#template-literal-types).

The offending `geo.d.ts` typedef file isn't actually usable as-is and it was only introduced in the latest release. So removing it should not have any practical impact.

I'll proceed cut a release with the fix within the next hour.

**Comment by achrinza** [comment]
`loopback-datasource-juggler@4.27.1` has been published:

- https://github.com/loopbackio/loopback-datasource-juggler/commit/92e05e6537e661094d1e4ebf206784ab2e6b2f34
- https://www.npmjs.com/package/loopback-datasource-juggler/v/4.27.1

**Comment by Anu1601CS** [comment]
@achrinza Thanks
