### ISSUE TITLE
Auto-discover auto_increment / identity field into property with generated = true and not be required

### ISSUE THREAD

**Issue by christiaanwesterbeek** [loopbackio/loopback-datasource-juggler#899]
Currently, when I discover a model from a SQL Server table with an identity field or a MySQL table  auto_increment field, that model will not have that field's `generated` property set to true.

I propose to change that. So that I when I discover a table with an auto numbered field into a fresh model. I can immediately do a Model.create without getting the error message _"The `model_name` instance is not valid. Details: `primary_key_name` can't be blank (value: null)."_

What we can do to accomplish that is to alter loopback-connector-xxx/lib/queryColumns to return also a `generated` boolean to capture if a column is auto numbered by the database.

For [mssql you'd add](http://stackoverflow.com/questions/87747/how-do-you-determine-what-sql-tables-have-an-identity-column-programatically):

```
COLUMNPROPERTY(object_id(table_schema+'.'+table_name), column_name, 'IsIdentity') AS generated
```

For [mysql you'd add](http://stackoverflow.com/questions/13772019/sql-check-if-a-column-auto-increments):

```
CASE WHEN extra LIKE '%auto_increment%' THEN 1 ELSE 0 END AS generated
```

Then here in loopback-datasource-juggler/lib/datasource.js method discoverSchemas at about line 1354, You'd change this

```
schema.properties[propName] = {
  type: item.type,
  required: (item.nullable === 'N' || item.nullable === 'NO'
  || item.nullable === 0 || item.nullable === false),
  length: item.dataLength,
  precision: item.dataPrecision,
  scale: item.dataScale
};
```

to

```
schema.properties[propName] = {
  type: item.type,
  required: (item.nullable === 'N' || item.nullable === 'NO'
  || item.nullable === 0 || item.nullable === false) && !item.generated,
  length: item.dataLength,
  precision: item.dataPrecision,
  scale: item.dataScale,
  generated: item.generated
};
```

(and in discoverSchemasSync too)

What do you think?

**Comment by Amir-61** [comment]
Hey @devotis,

I believe it would be much clear if you sent a PR and started the discussion on your PR; also please note when you mention the line number in this issue, they will not be valid after a while; in other words, code keeps changing and the line number you are referring to would not be valid after changes. Please send a PR to discuss the changes there.

Thanks a lot :-)

**Comment by loay** [comment]
- [x] MySQL https://github.com/strongloop/loopback-connector-mysql/pull/198
- [ ] MsSQL https://github.com/strongloop/loopback-connector-mssql/pull/100
- [ ] loopback-datasource-juggler https://github.com/strongloop/loopback-datasource-juggler/pull/1116

**Comment by fabianorodrigo** [comment]
Was this improvement done?

**Comment by devotis** [comment]
I guess not since PR https://github.com/strongloop/loopback-datasource-juggler/pull/1116 was not merged. To be honest, I lost interest. It's too simple of a commit, but the process is here is taking way too long. Check out the diff here. You can pick it up if you like.
